### PR TITLE
#162110676  Create Models for Todos 

### PR DESCRIPTION
**Pull request by fgkinus**
#### What does this PR do?
It adds a Core app and a List app. The core app contains reusable code throughout the application.
The Lists app has a new Model for Todos

#### What are the relevant pivotal tracker stories?
[#162110676](https://www.pivotaltracker.com/story/show/162110676)

### CODE REVIEW

**Comment by dmithamo** [comment]
Fix merge conflicts in `requirements.txt`

**Comment by gwako94** [comment]
A pr should have one commit message, put that into consideration in the future.
Nice structure.

**Comment by mashafrancis** [comment]
Nice PR structure.

**Comment by fabischolasi** [comment]
Add some more content on the PR messages. ie How the PR can be tested

**Comment by fabischolasi** [comment]
Vooala to the File structures

**Comment by GransonO** [comment]
Great start. however, give steps on how a new user would clone the repo and install all packages in the requirements.txt.

**Pull request merged**
